//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by devtools.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Microsoft.Extensions.Localization;
using System;

namespace Resources.Translations
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("devtools", "1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IpFilterTranslations : IIpFilterTranslations
    {
        private readonly IStringLocalizer<IpFilterTranslations> _stringLocalizer;

        public IpFilterTranslations(IStringLocalizer<IpFilterTranslations> stringLocalizer)
        {
            _stringLocalizer = stringLocalizer ?? throw new ArgumentNullException(nameof(stringLocalizer));
        }

        public string RejectionEmailActionDescriptionAndExpiration() => _stringLocalizer["rejection_email_action_description_and_expiration"];
        public string RejectionEmailActionDescriptionAndExpiration(object arg0, object arg1) => _stringLocalizer["rejection_email_action_description_and_expiration", arg0, arg1];
        public string RejectionEmailAuthorizeActionButton() => _stringLocalizer["rejection_email_authorize_action_button"];
        public string RejectionEmailGreetingsAndContext() => _stringLocalizer["rejection_email_greetings_and_context"];
        public string RejectionEmailGreetingsAndContext(object arg0, object arg1, object arg2, object arg3) => _stringLocalizer["rejection_email_greetings_and_context", arg0, arg1, arg2, arg3];
        public string RejectionEmailRejectActionButton() => _stringLocalizer["rejection_email_reject_action_button"];
        public string RejectionEmailSameDeviceWarning() => _stringLocalizer["rejection_email_same_device_warning"];
        public string RejectionEmailTitle() => _stringLocalizer["rejection_email_title"];

    }

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("devtools", "1.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public interface IIpFilterTranslations
    {
        /// <summary>
        /// UNFORMATTED Similar to: You can complete this request by clicking on one of the buttons.
        /// These links will expire on {0} at {1} .
        /// </summary>
        string RejectionEmailActionDescriptionAndExpiration();
        /// <summary>
        /// Similar to: You can complete this request by clicking on one of the buttons.
        /// These links will expire on {0} at {1} .
        /// </summary>
        string RejectionEmailActionDescriptionAndExpiration(object arg0, object arg1);
        /// <summary>
        /// Similar to: Allow this connection
        /// </summary>
        string RejectionEmailAuthorizeActionButton();
        /// <summary>
        /// UNFORMATTED Similar to: Hello {0},
        /// 
        /// You have requested a connection to Cloud Control from a new IP or device on {1} to {2}. 
        /// 
        /// &lt;b&gt;Ip: {3}.&lt;/b&gt;
        /// </summary>
        string RejectionEmailGreetingsAndContext();
        /// <summary>
        /// Similar to: Hello {0},
        /// 
        /// You have requested a connection to Cloud Control from a new IP or device on {1} to {2}. 
        /// 
        /// &lt;b&gt;Ip: {3}.&lt;/b&gt;
        /// </summary>
        string RejectionEmailGreetingsAndContext(object arg0, object arg1, object arg2, object arg3);
        /// <summary>
        /// Similar to: Report a fraudulent attempt
        /// </summary>
        string RejectionEmailRejectActionButton();
        /// <summary>
        /// Similar to: &lt;b&gt;Warning ! The login link must be open on the same device as when you first logged in to Cloudcontrol.&lt;/b&gt;
        /// </summary>
        string RejectionEmailSameDeviceWarning();
        /// <summary>
        /// Similar to: Connection request
        /// </summary>
        string RejectionEmailTitle();
    }
}