export enum CountsSortParamKey {
  Client = 'contract.client.name',
  Distributor = 'contract.distributor.name',
  Offer = 'offer.name',
  CountPeriod = 'countPeriod',
  NormalCount = 'number',
  EnhancedCount = 'accountingNumber',
  MinimalBilling = 'billingStrategy',
  UnitPrice = 'unitPrice',
  TotalBillable = 'totalBillableInEuro',
  TotalPartner = 'totalPartnerInEuro',
  TotalLucca = 'totalLuccaInEuro',
  ClientRebate = 'additionalRebate',
  DistributorRebate = 'distributorRebate',
}
