//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by devtools.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Microsoft.Extensions.Localization;
using System;

namespace Resources.Translations
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("devtools", "1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations : ITranslations
    {
        private readonly IStringLocalizer<Translations> _stringLocalizer;

        public Translations(IStringLocalizer<Translations> stringLocalizer)
        {
            _stringLocalizer = stringLocalizer ?? throw new ArgumentNullException(nameof(stringLocalizer));
        }

        public string EmailSyncReportErrorCount() => _stringLocalizer["email_sync_report_error_count"];
        public string EmailSyncReportErrorCount(object arg0) => _stringLocalizer["email_sync_report_error_count", arg0];
        public string EmailSyncReportTitle() => _stringLocalizer["email_sync_report_title"];

    }

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("devtools", "1.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public interface ITranslations
    {
        /// <summary>
        /// UNFORMATTED Similar to: {0} errors occurred while syncing CAFE.
        /// </summary>
        string EmailSyncReportErrorCount();
        /// <summary>
        /// Similar to: {0} errors occurred while syncing CAFE.
        /// </summary>
        string EmailSyncReportErrorCount(object arg0);
        /// <summary>
        /// Similar to: CAFE error sync report
        /// </summary>
        string EmailSyncReportTitle();
    }
}