export enum NavigationPath {
  Demos = 'demos',
  Environments = 'Environments',
  Counts = 'counts',
  Billing = 'billing',
  BillingSynthesis = 'synthesis',
  BillingToDo = 'to-do',
  BillingToExport = 'to-export',
  BillingExported = 'exported',
  Cmrr = 'cmrr',
  Contracts = 'contracts',
  ContractsManage = 'manage',
  ContractsDraft = 'create',
  Logs = 'logs',
  Offers = 'offers',
  Distributors = 'distributors',
  DistributorsManage = 'manage',
  DistributorsEnvironmentAccesses = 'environmentaccesses',
  Ftp = 'ftp',
  CodeSources = 'sources',
  Accounting = 'accounting',
  AccountingRevenue = 'revenue',
}
