// <auto-generated />
using System;
using Instances.Infra.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Instances.Infra.Migrations
{
    [DbContext(typeof(InstancesDbContext))]
    [Migration("20210714093131_CodeSourceAndArtifactViews")]
    partial class CodeSourceAndArtifactViews
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("instances")
                .HasAnnotation("ProductVersion", "3.1.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Distributors.Domain.Models.Distributor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnName("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DepartmentId")
                        .HasColumnName("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnName("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Distributors","shared");
                });

            modelBuilder.Entity("Instances.Domain.CodeSources.CodeSourceArtifacts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ArtifactType")
                        .HasColumnName("ArtifactType")
                        .HasColumnType("int");

                    b.Property<string>("ArtifactUrl")
                        .HasColumnName("ArtifactUrl")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<int>("CodeSourceId")
                        .HasColumnName("CodeSourceId")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .HasColumnName("FileName")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.HasIndex("CodeSourceId");

                    b.ToTable("CodeSourceArtifacts");
                });

            modelBuilder.Entity("Instances.Domain.CodeSources.CodeSourceConfig", b =>
                {
                    b.Property<int>("CodeSourceId")
                        .HasColumnType("int");

                    b.Property<string>("AppPath")
                        .HasColumnName("AppPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IisServerPath")
                        .HasColumnName("IisServerPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPrivate")
                        .HasColumnName("IsPrivate")
                        .HasColumnType("bit");

                    b.Property<string>("Subdomain")
                        .HasColumnName("Subdomain")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodeSourceId");

                    b.ToTable("CodeSourceConfigs");
                });

            modelBuilder.Entity("Instances.Domain.CodeSources.CodeSourceProductionVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BranchName")
                        .HasColumnName("BranchName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CodeSourceId")
                        .HasColumnName("CodeSourceId")
                        .HasColumnType("int");

                    b.Property<string>("CommitHash")
                        .HasColumnName("CommitHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnName("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("JenkinsBuildNumber")
                        .HasColumnName("JenkinsBuildNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CodeSourceId");

                    b.ToTable("CodeSourcesProductionVersions");
                });

            modelBuilder.Entity("Instances.Domain.Demos.Demo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId")
                        .HasColumnName("authorId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnName("comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnName("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeletionScheduledOn")
                        .HasColumnName("deletionScheduledOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DistributorId")
                        .HasColumnName("distributorID")
                        .HasColumnType("int");

                    b.Property<int>("InstanceID")
                        .HasColumnName("instanceId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnName("isActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTemplate")
                        .HasColumnType("bit");

                    b.Property<string>("Subdomain")
                        .HasColumnName("subdomain")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("DistributorId");

                    b.HasIndex("InstanceID")
                        .IsUnique();

                    b.ToTable("Demos");
                });

            modelBuilder.Entity("Instances.Domain.Demos.DemoDuplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId")
                        .HasColumnName("authorId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnName("comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnName("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InstanceDuplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnName("password")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<int>("SourceDemoId")
                        .HasColumnName("sourceDemoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InstanceDuplicationId");

                    b.ToTable("DemoDuplications");
                });

            modelBuilder.Entity("Instances.Domain.Instances.InstanceDuplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DistributorId")
                        .HasColumnName("distributorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnName("endedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Progress")
                        .HasColumnName("progress")
                        .HasColumnType("int");

                    b.Property<string>("SourceCluster")
                        .IsRequired()
                        .HasColumnName("sourceCluster")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceSubdomain")
                        .IsRequired()
                        .HasColumnName("sourceSubdomain")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<int>("SourceType")
                        .HasColumnName("sourceType")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnName("startedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TargetCluster")
                        .IsRequired()
                        .HasColumnName("targetCluster")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetSubdomain")
                        .IsRequired()
                        .HasColumnName("targetSubdomain")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<int>("TargetType")
                        .HasColumnName("targetType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DistributorId");

                    b.ToTable("InstanceDuplications");
                });

            modelBuilder.Entity("Instances.Domain.Instances.Models.Instance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AllUsersImposedPassword")
                        .HasColumnName("AllUsersImposedPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cluster")
                        .HasColumnName("Cluster")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EnvironmentId")
                        .HasColumnName("EnvironmentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnName("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAnonymized")
                        .HasColumnName("IsAnonymized")
                        .HasColumnType("bit");

                    b.Property<bool>("IsProtected")
                        .HasColumnName("IsProtected")
                        .HasColumnType("bit");

                    b.Property<int>("Type")
                        .HasColumnName("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Instances");
                });

            modelBuilder.Entity("Instances.Infra.Storage.Models.StoredCodeSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnName("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GithubRepo")
                        .HasColumnName("GithubRepo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JenkinsProjectName")
                        .HasColumnName("JenkinsProjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JenkinsProjectUrl")
                        .HasColumnName("JenkinsProjectUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Lifecycle")
                        .HasColumnName("Lifecycle")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnName("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnName("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CodeSources");
                });

            modelBuilder.Entity("Users.Domain.SimpleUser", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("PartenairesId")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnName("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnName("FirstName")
                        .HasColumnType("nvarchar(300)")
                        .HasMaxLength(300);

                    b.Property<bool>("IsActive")
                        .HasColumnName("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnName("LastName")
                        .HasColumnType("nvarchar(300)")
                        .HasMaxLength(300);

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Users","shared");
                });

            modelBuilder.Entity("Instances.Domain.CodeSources.CodeSourceArtifacts", b =>
                {
                    b.HasOne("Instances.Infra.Storage.Models.StoredCodeSource", null)
                        .WithMany("CodeSourceArtifacts")
                        .HasForeignKey("CodeSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Instances.Domain.CodeSources.CodeSourceConfig", b =>
                {
                    b.HasOne("Instances.Infra.Storage.Models.StoredCodeSource", null)
                        .WithOne("Config")
                        .HasForeignKey("Instances.Domain.CodeSources.CodeSourceConfig", "CodeSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Instances.Domain.CodeSources.CodeSourceProductionVersion", b =>
                {
                    b.HasOne("Instances.Infra.Storage.Models.StoredCodeSource", null)
                        .WithMany("ProductionVersions")
                        .HasForeignKey("CodeSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Instances.Domain.Demos.Demo", b =>
                {
                    b.HasOne("Users.Domain.SimpleUser", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Distributors.Domain.Models.Distributor", "Distributor")
                        .WithMany()
                        .HasForeignKey("DistributorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Instances.Domain.Instances.Models.Instance", "Instance")
                        .WithOne()
                        .HasForeignKey("Instances.Domain.Demos.Demo", "InstanceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Instances.Domain.Demos.DemoDuplication", b =>
                {
                    b.HasOne("Instances.Domain.Instances.InstanceDuplication", "InstanceDuplication")
                        .WithMany()
                        .HasForeignKey("InstanceDuplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Instances.Domain.Instances.InstanceDuplication", b =>
                {
                    b.HasOne("Distributors.Domain.Models.Distributor", "Distributor")
                        .WithMany()
                        .HasForeignKey("DistributorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
