// <auto-generated />
using System;
using AdvancedFilters.Infra.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AdvancedFilters.Infra.Migrations
{
    [DbContext(typeof(AdvancedFiltersDbContext))]
    [Migration("20210825162055_InitAdvancedFilters")]
    partial class InitAdvancedFilters
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("cafe")
                .HasAnnotation("ProductVersion", "3.1.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AdvancedFilters.Domain.Billing.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("ExternalId")
                        .HasColumnName("ExternalId")
                        .HasColumnType("uniqueidentifier")
                        .HasMaxLength(36);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RemoteId")
                        .HasColumnName("RemoteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("RemoteId")
                        .IsUnique();

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("AdvancedFilters.Domain.Billing.Models.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClientId")
                        .HasColumnName("ClientId")
                        .HasColumnType("int");

                    b.Property<int?>("ClientId1")
                        .HasColumnType("int");

                    b.Property<Guid>("ExternalId")
                        .HasColumnName("ExternalId")
                        .HasColumnType("uniqueidentifier")
                        .HasMaxLength(36);

                    b.Property<int>("RemoteId")
                        .HasColumnName("RemoteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ClientId1");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("AdvancedFilters.Domain.Billing.Models.EstablishmentContract", b =>
                {
                    b.Property<int>("ContractId")
                        .HasColumnName("ContractId")
                        .HasColumnType("int");

                    b.Property<int>("EstablishmentId")
                        .HasColumnName("EstablishmentId")
                        .HasColumnType("int");

                    b.HasKey("ContractId", "EstablishmentId");

                    b.ToTable("EstablishmentContracts");
                });

            modelBuilder.Entity("AdvancedFilters.Domain.Contacts.Models.AppContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AppInstanceId")
                        .HasColumnName("AppInstanceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnName("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnName("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnName("IsConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("RemoteId")
                        .HasColumnName("RemoteId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnName("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppInstanceId");

                    b.ToTable("AppContacts");
                });

            modelBuilder.Entity("AdvancedFilters.Domain.Contacts.Models.ClientContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("ClientId")
                        .HasColumnName("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnName("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnName("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnName("IsConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("RemoteId")
                        .HasColumnName("RemoteId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnName("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnName("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("ClientContacts");
                });

            modelBuilder.Entity("AdvancedFilters.Domain.Contacts.Models.SpecializedContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnName("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnName("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnName("IsConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("RemoteId")
                        .HasColumnName("RemoteId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnName("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnName("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SpecializedContacts");
                });

            modelBuilder.Entity("AdvancedFilters.Domain.Instance.Models.AppInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApplicationId")
                        .IsRequired()
                        .HasColumnName("ApplicationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnName("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EnvironmentId")
                        .HasColumnName("EnvironmentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RemoteId")
                        .HasColumnName("RemoteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("RemoteId")
                        .IsUnique();

                    b.ToTable("AppInstances");
                });

            modelBuilder.Entity("AdvancedFilters.Domain.Instance.Models.Environment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnName("Domain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnName("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("RemoteId")
                        .HasColumnName("RemoteId")
                        .HasColumnType("int");

                    b.Property<string>("Subdomain")
                        .IsRequired()
                        .HasColumnName("Subdomain")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RemoteId")
                        .IsUnique();

                    b.ToTable("Environments");
                });

            modelBuilder.Entity("AdvancedFilters.Domain.Instance.Models.Establishment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActivityCode")
                        .HasColumnName("ActivityCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .HasColumnName("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnName("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsArchived")
                        .HasColumnName("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("LegalIdentificationNumber")
                        .HasColumnName("LegalIdentificationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LegalUnitId")
                        .HasColumnName("LegalUnitId")
                        .HasColumnType("int");

                    b.Property<int?>("LegalUnitId1")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RemoteId")
                        .HasColumnName("RemoteId")
                        .HasColumnType("int");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasColumnName("TimeZoneId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsersCount")
                        .HasColumnName("UsersCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LegalUnitId");

                    b.HasIndex("LegalUnitId1");

                    b.HasIndex("RemoteId")
                        .IsUnique();

                    b.ToTable("Establishments");
                });

            modelBuilder.Entity("AdvancedFilters.Domain.Instance.Models.LegalUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActivityCode")
                        .HasColumnName("ActivityCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .HasColumnName("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnName("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnName("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EnvironmentId")
                        .HasColumnName("EnvironmentId")
                        .HasColumnType("int");

                    b.Property<int?>("EnvironmentId1")
                        .HasColumnType("int");

                    b.Property<int>("HeadquartersId")
                        .HasColumnName("HeadquartersId")
                        .HasColumnType("int");

                    b.Property<bool>("IsArchived")
                        .HasColumnName("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("LegalIdentificationNumber")
                        .HasColumnName("LegalIdentificationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnName("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RemoteId")
                        .HasColumnName("RemoteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("EnvironmentId1");

                    b.HasIndex("RemoteId")
                        .IsUnique();

                    b.ToTable("LegalUnits");
                });

            modelBuilder.Entity("AdvancedFilters.Domain.Billing.Models.Contract", b =>
                {
                    b.HasOne("AdvancedFilters.Domain.Billing.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .HasPrincipalKey("RemoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdvancedFilters.Domain.Billing.Models.Client", null)
                        .WithMany("Contracts")
                        .HasForeignKey("ClientId1");
                });

            modelBuilder.Entity("AdvancedFilters.Domain.Contacts.Models.AppContact", b =>
                {
                    b.HasOne("AdvancedFilters.Domain.Instance.Models.AppInstance", "AppInstance")
                        .WithMany()
                        .HasForeignKey("AppInstanceId")
                        .HasPrincipalKey("RemoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AdvancedFilters.Domain.Contacts.Models.ClientContact", b =>
                {
                    b.HasOne("AdvancedFilters.Domain.Billing.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .HasPrincipalKey("ExternalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AdvancedFilters.Domain.Instance.Models.AppInstance", b =>
                {
                    b.HasOne("AdvancedFilters.Domain.Instance.Models.Environment", "Environment")
                        .WithMany()
                        .HasForeignKey("EnvironmentId")
                        .HasPrincipalKey("RemoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AdvancedFilters.Domain.Instance.Models.Establishment", b =>
                {
                    b.HasOne("AdvancedFilters.Domain.Instance.Models.LegalUnit", "LegalUnit")
                        .WithMany()
                        .HasForeignKey("LegalUnitId")
                        .HasPrincipalKey("RemoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdvancedFilters.Domain.Instance.Models.LegalUnit", null)
                        .WithMany("Establishments")
                        .HasForeignKey("LegalUnitId1");
                });

            modelBuilder.Entity("AdvancedFilters.Domain.Instance.Models.LegalUnit", b =>
                {
                    b.HasOne("AdvancedFilters.Domain.Instance.Models.Environment", "Environment")
                        .WithMany()
                        .HasForeignKey("EnvironmentId")
                        .HasPrincipalKey("RemoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdvancedFilters.Domain.Instance.Models.Environment", null)
                        .WithMany("LegalUnits")
                        .HasForeignKey("EnvironmentId1");
                });
#pragma warning restore 612, 618
        }
    }
}
